DROP TABLE IF EXISTS API_KEYS;
CREATE TABLE API_KEYS(API_KEY VARCHAR(255) PRIMARY KEY, API_HASH VARCHAR(255),LAST_ATTEMPT LONG, ATTEMPTS INT,SUCCESSFUL_ATTEMPT LONG);
INSERT INTO API_KEYS VALUES('jack', '$2a$10$uCQhnAlQmES9VoTQJHXY6.D0meCFcd/hearkol98EMvUAK9lknvtm',0,0,0);
INSERT INTO API_KEYS VALUES('james', '$2a$10$XyLuHVJHgjxzKbMhyTGideLo1pLJ4kHiAACSNgYO4Z3fxKz8pGNQC',0,0,0);
-- SELECT * FROM API_KEYS ORDER BY API_KEY;
-- UPDATE TEST SET NAME='Hi' WHERE ID=1;
-- DELETE FROM TEST WHERE ID=2;
DROP TABLE IF EXISTS Encryption_Table;
CREATE TABLE Encryption_Table(ID INT AUTO_INCREMENT PRIMARY Key ,APP_NAME VARCHAR(255), SECRET_KEY VARCHAR(255), ENCRYPT_KEY VARCHAR(255),SALT VARCHAR(255));
INSERT INTO Encryption_Table VALUES(default, 'app1','k1', 'GnUC4BQ91g627I5LTnEH1M9lJd2HaoQhgi+WDowOA/A=	','6+UQqFGpyrdhPUnLO7fT+Q==');
INSERT INTO Encryption_Table VALUES(default, 'app2','k4', 'qkElDrWtmDKYE6/7KCr6zJEJvGtP6GVeRTLuhWTpZeY=','kOuF1EAmlxDclAxlgwNDXg==');


DROP TABLE IF EXISTS Auth_Table;
CREATE TABLE Auth_Table(ID INT AUTO_INCREMENT primary key, APP_NAME VARCHAR(255),API_KEY VARCHAR(255),KEY_ROLE VARCHAR(255));
INSERT INTO Auth_Table VALUES(default,'app1','jack', 'User');
INSERT INTO Auth_Table VALUES(default,'app2','james', 'Admin');
INSERT INTO Auth_Table VALUES(default,'Admin','james', 'Admin');
INSERT INTO Auth_Table VALUES(default,'app1','james', 'Admin');
-- INSERT INTO Auth_Table VALUES('Admin','james', 'Admin');

